//
//  UserProductListInteractor.swift
//  Alysei
//
//  Created by SHALINI YADAV on 6/14/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserProductListBusinessLogic
{
  func doSomething(request: UserProductList.Something.Request)
}

protocol UserProductListDataStore
{
  //var name: String { get set }
}

class UserProductListInteractor: UserProductListBusinessLogic, UserProductListDataStore
{
  var presenter: UserProductListPresentationLogic?
  var worker: UserProductListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: UserProductList.Something.Request)
  {
    worker = UserProductListWorker()
    worker?.doSomeWork()
    
    let response = UserProductList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
