//
//  BasicConnectFlowPresenter.swift
//  Alysei
//
//  Created by Janu Gandhi on 11/06/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BasicConnectFlowPresentationLogic {
}

class BasicConnectFlowPresenter: BasicConnectFlowPresentationLogic {
    weak var viewController: BasicConnectFlowDisplayLogic?
    
    // MARK:- protocol methods
    
}
