//
//  BasicConnectFlowWorker.swift
//  Alysei
//
//  Created by Janu Gandhi on 11/06/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BasicConnectFlowWorker {
//    func makeAPICall(_ urlRequest: URLRequest, complition: @escaping (Data?, Error?) -> ()) {
//        WebServices.shared.request(urlRequest) { data, urlResponse, statusCode, error in
//            complition(data, error)
//        }
//    }
}
