//
//  BasicConnectFlowInteractor.swift
//  Alysei
//
//  Created by Janu Gandhi on 11/06/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BasicConnectFlowBusinessLogic {
}

protocol BasicConnectFlowDataStore {
    //var name: String { get set }
}

class BasicConnectFlowInteractor: BasicConnectFlowBusinessLogic, BasicConnectFlowDataStore {
    var presenter: BasicConnectFlowPresentationLogic?
    var worker: BasicConnectFlowWorker?
    //var name: String = ""

    // MARK:- protocol methods
}
