//
//  BasicConnectFlowRouter.swift
//  Alysei
//
//  Created by Janu Gandhi on 11/06/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BasicConnectFlowRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol BasicConnectFlowDataPassing {
    var dataStore: BasicConnectFlowDataStore? { get }
}

class BasicConnectFlowRouter: NSObject, BasicConnectFlowRoutingLogic, BasicConnectFlowDataPassing {
    weak var viewController: BasicConnectFlowViewController?
    var dataStore: BasicConnectFlowDataStore?

    // MARK: Routing

    //func routeToSomewhere(segue: UIStoryboardSegue?) {
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}

    // MARK: Navigation

    //func navigateToSomewhere(source: BasicConnectFlowViewController, destination: SomewhereViewController) {
    //  source.show(destination, sender: nil)
    //}

    // MARK: Passing data

    //func passDataToSomewhere(source: BasicConnectFlowDataStore, destination: inout SomewhereDataStore) {
    //  destination.name = source.name
    //}
}
