//
//  SharePostModels.swift
//  Alysei
//
//  Created by Janu Gandhi on 20/08/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SharePost {
    // MARK: Use cases
    
    enum Share {
        struct RequestModel: Codable {
            var privacyLabel: String
            var actionType: String
            var postID: Int
            var body: String?

            private enum CodingKeys: String, CodingKey {
                case privacyLabel = "privacy"
                case actionType = "action_type"
                case postID = "shared_post_id"
                case body = "body"
            }

        }
        struct Response {
        }
        struct ViewModel {
        }
    }

    enum PostData {
        struct post {
            var attachments: [Attachments]?
            var postOwnerDetail: SubjectData?
            var postDescription: String?
            var postID: Int
        }
    }
}
