//
//  SharePostInteractor.swift
//  Alysei
//
//  Created by Janu Gandhi on 20/08/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SharePostBusinessLogic {
    func sharePost(_ model: SharePost.Share.RequestModel)
}

protocol SharePostDataStore {
    //var name: String { get set }
}

class SharePostInteractor: SharePostBusinessLogic, SharePostDataStore {
    var presenter: SharePostPresentationLogic?
    var worker: SharePostWorker?
    //var name: String = ""

    // MARK:- protocol methods

    func sharePost(_ model: SharePost.Share.RequestModel) {

        let url = APIUrl.Posts.sharePost
        guard var urlRequest = WebServices.shared.buildURLRequest(url, method: .POST) else {
            return
        }

        urlRequest.setValue("application/x-www-form-urlencoded", forHTTPHeaderField: "Content-Type")
        do {

            let body = try JSONEncoder().encode(model)

            urlRequest.httpBody = body
            WebServices.shared.request(urlRequest) { data, urlResponse, statusCode, error in
                self.presenter?.postShared()
            }

        } catch {
            print(error.localizedDescription)
        }





    }
}
