//
//  SharePostPresenter.swift
//  Alysei
//
//  Created by Janu Gandhi on 20/08/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SharePostPresentationLogic {
}

class SharePostPresenter: SharePostPresentationLogic {
    weak var viewController: SharePostDisplayLogic?
    
    // MARK:- protocol methods
    
}
