//
//  MyStoreProductInteractor.swift
//  Alysei
//
//  Created by SHALINI YADAV on 6/24/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyStoreProductBusinessLogic
{
  func doSomething(request: MyStoreProduct.Something.Request)
}

protocol MyStoreProductDataStore
{
  //var name: String { get set }
}

class MyStoreProductInteractor: MyStoreProductBusinessLogic, MyStoreProductDataStore
{
  var presenter: MyStoreProductPresentationLogic?
  var worker: MyStoreProductWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MyStoreProduct.Something.Request)
  {
    worker = MyStoreProductWorker()
    worker?.doSomeWork()
    
    let response = MyStoreProduct.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
