//
//  EventsInteractor.swift
//  Alysei
//
//  Created by Janu Gandhi on 15/04/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EventsBusinessLogic {
}

protocol EventsDataStore {
    //var name: String { get set }
}

class EventsInteractor: EventsBusinessLogic, EventsDataStore {
    var presenter: EventsPresentationLogic?
    var worker: EventsWorker?
    //var name: String = ""

    // MARK:- protocol methods
}
