//
//  EventsPresenter.swift
//  Alysei
//
//  Created by Janu Gandhi on 15/04/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EventsPresentationLogic {
}

class EventsPresenter: EventsPresentationLogic {
    weak var viewController: EventsDisplayLogic?
    
    // MARK:- protocol methods
    
}
