//
//  PostCommentsPresenter.swift
//  Alysei
//
//  Created by Shivani Vohra Gandhi on 11/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostCommentsPresentationLogic {
}

class PostCommentsPresenter: PostCommentsPresentationLogic {
    weak var viewController: PostCommentsDisplayLogic?
    
    // MARK:- protocol methods
    
}
