//
//  ConnectionProductTypeInteractor.swift
//  Alysei
//
//  Created by SHALINI YADAV on 6/14/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConnectionProductTypeBusinessLogic
{
    func doSomething(request: ConnectionProductType.Something.Request)
    func showConnectionProduct()
}

protocol ConnectionProductTypeDataStore
{
    //var name: String { get set }
}

class ConnectionProductTypeInteractor: ConnectionProductTypeBusinessLogic, ConnectionProductTypeDataStore
{
    
    var presenter: ConnectionProductTypePresentationLogic?
    var worker: ConnectionProductTypeWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: ConnectionProductType.Something.Request)
    {
        worker = ConnectionProductTypeWorker()
        worker?.doSomeWork()
        
        let response = ConnectionProductType.Something.Response()
        presenter?.presentSomething(response: response)
    }
    
    func showConnectionProduct(){
        do {
            let urlString = APIUrl.Connection.kProductTypeCategory

            guard let request = WebServices.shared.buildURLRequest(urlString, method: .GET) else {
                return
            }
            print("urlRequest-----------------------------------\(request)")
            WebServices.shared.request(request) { data, URLResponse, statusCode, error in
                print("Show Product Screen--------------------------\(data ?? Data())")
                self.presenter?.showProductCategory(data, true)
            }
        } catch {
            print(error.localizedDescription)
        }

    }
}
