//
//  ConnectionProductTypeRouter.swift
//  Alysei
//
//  Created by SHALINI YADAV on 6/14/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ConnectionProductTypeRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    
    func routeToProductScreen()
}

protocol ConnectionProductTypeDataPassing
{
  var dataStore: ConnectionProductTypeDataStore? { get }
}

class ConnectionProductTypeRouter: NSObject, ConnectionProductTypeRoutingLogic, ConnectionProductTypeDataPassing
{
    
  weak var viewController: ConnectionProductTypeViewController?
  var dataStore: ConnectionProductTypeDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}
    
    func routeToProductScreen() {
     print("Route-----------------------------------")
    }
    
  // MARK: Navigation
  
  //func navigateToSomewhere(source: ConnectionProductTypeViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: ConnectionProductTypeDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
