//
//  ConnectionProductTypeViewController.swift
//  Alysei
//
//  Created by SHALINI YADAV on 6/14/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConnectionProductTypeDisplayLogic: class
{
  func displaySomething(viewModel: ConnectionProductType.Something.ViewModel)
    func   displayProductData(_ productData: Data?)
}

class ConnectionProductTypeViewController: UIViewController, ConnectionProductTypeDisplayLogic
{
    
    
  var interactor: ConnectionProductTypeBusinessLogic?
  var router: (NSObjectProtocol & ConnectionProductTypeRoutingLogic & ConnectionProductTypeDataPassing)?
    
   
    //var userModel: BasicConnectFlow.userDataModel!
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ConnectionProductTypeInteractor()
    let presenter = ConnectionProductTypePresenter()
    let router = ConnectionProductTypeRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var vwProduct : UIView!
  
  func doSomething()
  {
    let request = ConnectionProductType.Something.Request()
    interactor?.doSomething(request: request)
    
    vwProduct.layer.borderWidth = 0.5
    vwProduct.layer.borderColor = UIColor.lightGray.cgColor
  }
  
  func displaySomething(viewModel: ConnectionProductType.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    
    func displayProductData(_ productData: Data?) {
        print("Show Data")
        router?.routeToProductScreen()
    }
    
    @IBAction func btnBackAction(_ sender: UIButton){
        self.navigationController?.popViewController(animated: true)
    }
    
    @IBAction func confirmButtonTapped(_ sender: UIButton) {


    }
    
    @IBAction func viewProductTapped(_ sender: UIButton) {
        
        self.interactor?.showConnectionProduct()

    }
}
