//
//  MyStoreDetailPresenter.swift
//  Alysei
//
//  Created by SHALINI YADAV on 6/24/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyStoreDetailPresentationLogic
{
  func presentSomething(response: MyStoreDetail.Something.Response)
}

class MyStoreDetailPresenter: MyStoreDetailPresentationLogic
{
  weak var viewController: MyStoreDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MyStoreDetail.Something.Response)
  {
    let viewModel = MyStoreDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
