//
//  MyStoreDetailInteractor.swift
//  Alysei
//
//  Created by SHALINI YADAV on 6/24/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyStoreDetailBusinessLogic
{
  func doSomething(request: MyStoreDetail.Something.Request)
}

protocol MyStoreDetailDataStore
{
  //var name: String { get set }
}

class MyStoreDetailInteractor: MyStoreDetailBusinessLogic, MyStoreDetailDataStore
{
  var presenter: MyStoreDetailPresentationLogic?
  var worker: MyStoreDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MyStoreDetail.Something.Request)
  {
    worker = MyStoreDetailWorker()
    worker?.doSomeWork()
    
    let response = MyStoreDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
