//
//  MyStoreInquiriesInteractor.swift
//  Alysei
//
//  Created by SHALINI YADAV on 6/24/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyStoreInquiriesBusinessLogic
{
  func doSomething(request: MyStoreInquiries.Something.Request)
}

protocol MyStoreInquiriesDataStore
{
  //var name: String { get set }
}

class MyStoreInquiriesInteractor: MyStoreInquiriesBusinessLogic, MyStoreInquiriesDataStore
{
  var presenter: MyStoreInquiriesPresentationLogic?
  var worker: MyStoreInquiriesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MyStoreInquiries.Something.Request)
  {
    worker = MyStoreInquiriesWorker()
    worker?.doSomeWork()
    
    let response = MyStoreInquiries.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
