//
//  ContactDetailViewController.swift
//  Alysei
//
//  Created by Janu Gandhi on 07/04/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactDetailDisplayLogic: class {
}

class ContactDetailViewController: UIViewController, ContactDetailDisplayLogic {
    var interactor: ContactDetailBusinessLogic?
    var router: (NSObjectProtocol & ContactDetailRoutingLogic & ContactDetailDataPassing)?

    var viewModel: ContactDetail.Contact.ViewModel!
    // MARK:- Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK:- Setup

    private func setup() {
        let viewController = self
        let interactor = ContactDetailInteractor()
        let presenter = ContactDetailPresenter()
        let router = ContactDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK:- View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        if viewModel != nil {
            self.emailTextField.text = "\(viewModel.email)"
            self.phoneTextField.text = "\(viewModel.phone ?? "")"
            self.addressTextField.text = "\(viewModel.address ?? "")"
            self.websiteTextField.text = "\(viewModel.websiteURL ?? "")"
            self.facebookTextField.text = "\(viewModel.facebookURL ?? "")"
        }
    }

//     MARK:- IBOutlets
    @IBOutlet var emailTextField: UITextFieldExtended!
    @IBOutlet var phoneTextField: UITextFieldExtended!
    @IBOutlet var addressTextField: UITextFieldExtended!
    @IBOutlet var websiteTextField: UITextFieldExtended!
    @IBOutlet var facebookTextField: UITextFieldExtended!

    // MARK:- protocol methods


    // MARK:- @IBAction methods
    @IBAction func saveButtonTapped(_ sender: UIButton) {
        
    }
    
}
