//
//  ContactDetailInteractor.swift
//  Alysei
//
//  Created by Janu Gandhi on 07/04/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactDetailBusinessLogic {
}

protocol ContactDetailDataStore {
    //var name: String { get set }
}

class ContactDetailInteractor: ContactDetailBusinessLogic, ContactDetailDataStore {
    var presenter: ContactDetailPresentationLogic?
    var worker: ContactDetailWorker?
    //var name: String = ""

    // MARK:- protocol methods
}
