//
//  ContactDetailModels.swift
//  Alysei
//
//  Created by Janu Gandhi on 07/04/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ContactDetail {
    // MARK: Use cases
    
    enum Contact {
        struct Request {
        }
        struct Response: Codable {
            var email: String
            var phone: String?
            var address: String?
            var website: String?
            var fb_link: String?
        }
        struct ViewModel: Codable {
            var response: Response
            var email: String
            var phone: String? { response.phone }
            var address: String? { response.address }
            var websiteURL: String? { response.website }
            var facebookURL: String? { response.fb_link }
        }
    }
}
