//
//  ContactDetailInteractor.swift
//  Alysei
//
//  Created by Janu Gandhi on 07/04/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactDetailBusinessLogic {
    func updateContactDetail(_ requestModel: ContactDetail.Contact.Request)
}

protocol ContactDetailDataStore {
    //var name: String { get set }
}

class ContactDetailInteractor: ContactDetailBusinessLogic, ContactDetailDataStore {
    var presenter: ContactDetailPresentationLogic?
    var worker: ContactDetailWorker?
    //var name: String = ""

    // MARK:- protocol methods

    func updateContactDetail(_ requestModel: ContactDetail.Contact.Request) {
        guard var urlRequest = WebServices.shared.buildURLRequest("\(APIUrl.Profile.updateContactDetails)", method: .POST) else { return }
        urlRequest.httpBody = requestModel.data()
        WebServices.shared.request(urlRequest) { (data, response, statusCode, error)  in
            print(error)
            print(statusCode)
        }
    }
}
