//
//  ContactDetailPresenter.swift
//  Alysei
//
//  Created by Janu Gandhi on 07/04/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactDetailPresentationLogic {
    func contactInfoUpdated(_ status: Bool)
}

class ContactDetailPresenter: ContactDetailPresentationLogic {
    weak var viewController: ContactDetailDisplayLogic?
    
    // MARK:- protocol methods

    func contactInfoUpdated(_ status: Bool) {
        var message = "Your info has been updated."
        if !status {
            message = "Error while updating contact info."
        }
        
        self.viewController?.showAlertWithMessage(message)

    }
    
}
